services:
  app-prod:
    image: climateseals-ai:production
    build:
      context: .
      dockerfile: Dockerfile
      target: climateseals-ai-production  
    ports:
      - '5173:5173'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5173
      - RUNNING_IN_DOCKER=true
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: pnpm run dockerstart
    profiles:
      - production

  app-dev:
    image: climateseals-ai-development:v1
    build:
      target: climateseals-ai-development
    env_file: '.env'
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=5173
      - RUNNING_IN_DOCKER=true
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
      - /app/node_modules
    ports:
      - '5173:5173'
    command: pnpm run dev --host 0.0.0.0
    profiles: ['development', 'default']

  app-prebuild:
    image: crpi-bvovg2g7y33dn86o.cn-shanghai.personal.cr.aliyuncs.com/climateseal/production:prodiction
    build:
      context: .
      dockerfile: Dockerfile
      target: climateseals-ai-production
    ports:
      - '5173:5173'
    env_file: '.env'
    environment:
      - NODE_ENV=production
      - PORT=5173
      - RUNNING_IN_DOCKER=true
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-info}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: pnpm run dockerstart
    profiles:
      - prebuilt
